### ISSUE TITLE
Hammer stopped breaking ores

### ISSUE THREAD

**Issue by Ectalite** [TeamAOF/All-of-Fabric-3#23]
After updating to latest 1.4.2 version, Hammer wouldn't work properly and stopped breaking ores. (I tested with obsidian and diamond hammers). They can however break vanilla ores.

**Comment by AK9Official** [comment]
Looking into it, I’m pretty sure I know what is causing it..

**Comment by Ectalite** [comment]
We also saw that the GUI to change aspect (identity mod) is broken.

**Comment by AK9Official** [comment]
fixed in next update

**Comment by Ectalite** [comment]
I'm playing on the latest modpack version (1.5.1) and the hammer issue remains.
