### ISSUE TITLE
Client crash with Terrarian Slime glowstick with a Bits and Chisels bit collection block.

### ISSUE THREAD

**Issue by irunatbullets** [TeamAOF/All-of-Fabric-3#379]
Steps to reproduce.

- With a chisel create a bit collection block by taking some bits from any block and constructing a shape somewhere else.
- Take the little constructed shape - this is your bit collection.
- Throw down a glowstick on the ground.
- Highlight the bit collection in your hotbar.
- Right-click the glowstick with it.
- Enjoy your desktop wallpaper.

https://paste.alloffabric.com/ovimuhogiy.yaml

**Comment by Monster-Zer0** [comment]
resolved with 1.7b update

**Comment by irunatbullets** [comment]
Still occurs with 1.8b

https://paste.alloffabric.com/yuyarulelo.yaml
